### ISSUE TITLE
Multiple groups with draggable items : drag all group instead of items

### ISSUE THREAD

**Issue by invaders-xx** [nextapps-be/livewire-sortablejs#3] opened 2021-11-30 15:20 UTC
Dear all,

Many thanks for this great and very useful package.

I have 2 questions:
1) Is it possible to implement dragging of group of items ?
2) When moving an item from one group to another, how to handle the previous location of this item within the structure ?

Many thanks in advance for you feedback,

BR 
David

**Comment by gdebrauwer** [comment] 2022-02-05 13:17
> Is it possible to implement dragging of group of items ?

Yes, it is possible to do this, but it was not documented in the readme file yet. I updated the documentation, you can find it [here](https://github.com/nextapps-be/livewire-sortablejs/blob/master/README.md#multiple-draggable-groups-with-draggable-items).

> When moving an item from one group to another, how to handle the previous location of this item within the structure ?

What do you mean by this? Do you have an example?

**Comment by invaders-xx** [comment] 2022-02-08 08:39
Example: I have a group A with items 1, 2, 3 and a group B with no item
I move item 2 from group A to B. How do I know in the result array that 2 is coming from A ? Because on the backend, I have to remove it from A and add it to B.

I hope I made myself clear.

Thanks for help

**Comment by gdebrauwer** [comment] 2022-02-13 14:32
In your blade file, you know which items belongs to which group, so you should be able to know that in your Livewire component class as well before you process the updated order

**Comment by gdebrauwer** [comment] 2023-10-19 13:54
Duplicate of https://github.com/nextapps-be/livewire-sortablejs/issues/5

**Closed by gdebrauwer** 2023-10-19 13:54 UTC
